### ISSUE TITLE
purchased flatify theme - not received anything

### ISSUE THREAD

**Issue by pareshc** [iarouse/dist-flatify#2]
Hi,
Last week, i purchased the Flatify theme from Wrapbootstrap, and i have not received any emails or links for my account activation or for the purchased theme. I have emailed support@wrapbootstrap.com a few times, and still no luck. Hense why I am now creating an issue here. I know this is not related to a  bug, but am getting frustrated. 
I paid via paypal.

Any help would be appreciated.

regard
Paresh

**Comment by iarouse** [comment]
Hi Paresh,  

For purchase related question, you can contact wrapBootstrap support https://wrapbootstrap.com/support, you can probably get your downloads here: https://wrapbootstrap.com/support/download-resender

Hope this helps :)

## cheers

arousing

**Comment by tamoyal** [comment]
@iarouse Your theme documentation says to contact you with any questions (which I have a few) but you do not give contact information.  How do you expect users to find you?

**Comment by iarouse** [comment]
Hi, if you bought my item through wrapBootstrap.

You can either leave a comment at comment section on wrapBootstrap site or
message me through my wrapBootstrap profile page.

Also, thanks for your feedback,  I didn't realize it will be hard for
buyers to find the ways to contact me, I'll add the link to documentation
later.

Hope this helps :)

**Comment by pareshc** [comment]
Thanks..
It took a while to get my account activated. and then once it was done, I
could download the theme.
I really like your themes and would be purchasing more in the future.

thanks
Paresh

On Wed, Jan 21, 2015 at 11:11 AM, iarouse notifications@github.com wrote:

> Hi, if you bought my item through wrapBootstrap.
> 
> You can either leave a comment at comment section on wrapBootstrap site or
> message me through my wrapBootstrap profile page.
> 
> Also, thanks for your feedback, I didn't realize it will be hard for
> buyers to find the ways to contact me, I'll add the link to documentation
> later.
> 
> Hope this helps :)
> 
> On Mon, Jan 19, 2015 at 3:47 AM, Tony Amoyal notifications@github.com
> wrote:
> 
> > @iarouse https://github.com/iarouse Your theme documentation says to
> > contact you with any questions (which I have a few) but you do not give
> > contact information. How do you expect users to find you?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/iarouse/dist-flatify/issues/2#issuecomment-70461384.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iarouse/dist-flatify/issues/2#issuecomment-70761226.

## 

---

An expert is someone who takes a subject you understand and makes it sound
confusing.

**Comment by iarouse** [comment]
Cool and glad you like it :)
